### PR TITLE
support older browsers

### PR DESCRIPTION
**Pull request by tunnckoCore**
like https://github.com/jonschlinkert/kind-of/pull/2

### CODE REVIEW

**Comment by jonschlinkert** [comment]
what happens if it is an array and `Array.isArray()` doesn't exist?

I think we'll want to merge your pr into kind-of, then use `typeOf(val) === 'array'`, sound good?

**Comment by tunnckoCore** [comment]
mm yep, sounds better :+1:

**Comment by jonschlinkert** [comment]
closing based on https://github.com/jonschlinkert/falsey/pull/1#issuecomment-85869385 (correct?)

**Comment by tunnckoCore** [comment]
mm yep

**Pull request closed without merging**
